### ISSUE TITLE
Epic #1

### ISSUE THREAD

**Issue by Miguel-Fontes** [Miguel-Fontes/issue-management-template#1]
Epic description (no pun intended).

- [ ] Epic Task 1 (https://github.com/Miguel-Fontes/issue-management-template/issues/2)
- [ ] Epic Task 2 (https://github.com/Miguel-Fontes/issue-management-template/issues/3)
- [ ] Epic Task 3 (https://github.com/Miguel-Fontes/issue-management-template/issues/4)
