### ISSUE TITLE
Epic #2

### ISSUE THREAD

**Issue by Miguel-Fontes** [Miguel-Fontes/issue-management-template#5]
Epic description (no pun intended).
- [ ] Task 1 (https://github.com/Miguel-Fontes/issue-management-template/issues/6)
- [ ] Task 2 (https://github.com/Miguel-Fontes/issue-management-template/issues/7)
- [ ] Task 3 (https://github.com/Miguel-Fontes/issue-management-template/issues/8)
